//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlkemyDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_account
    {
        public int user_account { get; set; }
        public string password { get; set; }
    
        public virtual access access { get; set; }
    }
}
