//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlkemyDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class classes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public classes()
        {
            this.classes_registry = new HashSet<classes_registry>();
        }
    
        public int class_code { get; set; }
        public int class_professor_dni { get; set; }
        public Nullable<int> class_quota { get; set; }
        public System.DateTime class_schedule { get; set; }
        public string class_name { get; set; }
    
        public virtual professors_table professors_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<classes_registry> classes_registry { get; set; }
    }
}
