//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        public int file_number { get; set; }
        public Nullable<int> student_ID { get; set; }
        public string student_name { get; set; }
        public string student_last_name { get; set; }
    
        public virtual classes classes { get; set; }
    }
}
